namespace ReisProduction.Wincore.Utilities.Enums;
public enum InputType : ushort
{
    None = VirtualKey.None,
    LeftButton = VirtualKey.LeftButton,
    RightButton = VirtualKey.RightButton,
    Cancel = VirtualKey.Cancel,
    MiddleButton = VirtualKey.MiddleButton,
    XButton1 = VirtualKey.XButton1,
    XButton2 = VirtualKey.XButton2,
    MouseScrollLeft = 0xFF00,
    MouseScrollRight = 0xFF01,
    MouseScrollUp = 0xFF02,
    MouseScrollDown = 0xFF03,
    MouseNavigateLeft = 0xFF04,
    MouseNavigateLeftSmooth = 0xFF05,
    MouseNavigateRight = 0xFF06,
    MouseNavigateRightSmooth = 0xFF07,
    MouseNavigateUp = 0xFF08,
    MouseNavigateUpSmooth = 0xFF09,
    MouseNavigateDown = 0xFF10,
    MouseNavigateDownSmooth = 0xFF11,
    MouseNavigateToXY = 0xFF12,
    MouseNavigateToXYSmooth = 0xFF13,
    Back = VirtualKey.Back,
    Tab = VirtualKey.Tab,
    Escape = VirtualKey.Escape,
    Clear = VirtualKey.Clear,
    Enter = VirtualKey.Enter,
    Shift = VirtualKey.Shift,
    LeftShift = VirtualKey.LeftShift,
    RightShift = VirtualKey.RightShift,
    Control = VirtualKey.Control,
    LeftControl = VirtualKey.LeftControl,
    RightControl = VirtualKey.RightControl,
    Menu = VirtualKey.Menu,
    LeftMenu = VirtualKey.LeftMenu,
    RightMenu = VirtualKey.RightMenu,
    LeftWindows = VirtualKey.LeftWindows,
    RightWindows = VirtualKey.RightWindows,
    Pause = VirtualKey.Pause,
    CapitalLock = VirtualKey.CapitalLock,
    Kana = VirtualKey.Kana,
    Hanja = VirtualKey.Hanja,
    Convert = VirtualKey.Convert,
    NonConvert = VirtualKey.NonConvert,
    Accept = VirtualKey.Accept,
    ModeChange = VirtualKey.ModeChange,
    Space = VirtualKey.Space,
    PageUp = VirtualKey.PageUp,
    PageDown = VirtualKey.PageDown,
    End = VirtualKey.End,
    Home = VirtualKey.Home,
    Left = VirtualKey.Left,
    Up = VirtualKey.Up,
    Right = VirtualKey.Right,
    Down = VirtualKey.Down,
    Select = VirtualKey.Select,
    Print = VirtualKey.Print,
    Execute = VirtualKey.Execute,
    Snapshot = VirtualKey.Snapshot,
    Insert = VirtualKey.Insert,
    Delete = VirtualKey.Delete,
    Help = VirtualKey.Help,
    Number0 = VirtualKey.Number0,
    Number1 = VirtualKey.Number1,
    Number2 = VirtualKey.Number2,
    Number3 = VirtualKey.Number3,
    Number4 = VirtualKey.Number4,
    Number5 = VirtualKey.Number5,
    Number6 = VirtualKey.Number6,
    Number7 = VirtualKey.Number7,
    Number8 = VirtualKey.Number8,
    Number9 = VirtualKey.Number9,
    A = VirtualKey.A, B = VirtualKey.B, C = VirtualKey.C, Ç = 0xDC, D = VirtualKey.D, E = VirtualKey.E, F = VirtualKey.F,
    G = VirtualKey.G, Ğ = 0xDB, H = VirtualKey.H, I = VirtualKey.I, İ = 0xDE, J = VirtualKey.J, K = VirtualKey.K,
    L = VirtualKey.L, M = VirtualKey.M, N = VirtualKey.N, O = VirtualKey.O, Ö = 0xBF, P = VirtualKey.P, Q = VirtualKey.Q,
    R = VirtualKey.R, S = VirtualKey.S, Ş = 0xBA, T = VirtualKey.T, U = VirtualKey.U, Ü = 0xDD, V = VirtualKey.V,
    W = VirtualKey.W, X = VirtualKey.X, Y = VirtualKey.Y, Z = VirtualKey.Z,
    Application = VirtualKey.Application,
    Sleep = VirtualKey.Sleep,
    NumberPad0 = VirtualKey.NumberPad0,
    NumberPad1 = 0x61,
    NumberPad2 = 0x62,
    NumberPad3 = 0x63,
    NumberPad4 = 0x64,
    NumberPad5 = 0x65,
    NumberPad6 = 0x66,
    NumberPad7 = 0x67,
    NumberPad8 = 0x68,
    NumberPad9 = 0x69,
    NumberKeyLock = 0x90,
    Multiply = 0x6A,
    Add = 0x6B,
    Separator = 0x6C,
    Subtract = 0x6D,
    Decimal = 0x6E,
    Divide = 0x6F,
    F1 = 0x70, F2 = 0x71, F3 = 0x72, F4 = 0x73, F5 = 0x74, F6 = 0x75,
    F7 = 0x76, F8 = 0x77, F9 = 0x78, F10 = 0x79, F11 = 0x7A, F12 = 0x7B,
    F13 = 0x7C, F14 = 0x7D, F15 = 0x7E, F16 = 0x7F, F17 = 0x80, F18 = 0x81,
    F19 = 0x82, F20 = 0x83, F21 = 0x84, F22 = 0x85, F23 = 0x86, F24 = 0x87,
    Scroll = 0x91,
    Oem1 = Ş,           // ;: (In Turkish keyboard Ş)
    OemPlus = 0xBB,     // +
    OemComma = 0xBC,    // ,
    OemMinus = 0xBD,    // -
    OemPeriod = 0xBE,   // .
    Oem2 = Ö,           // / or Ö (In Turkish keyboard Ö)
    Oem3 = 0xC0,        // ` or ^
    Oem4 = Ğ,           // [ { or Ğ
    Oem5 = Ç,           // \ | or Ç
    Oem6 = Ü,           // ] } or Ü
    Oem7 = İ,           // ' " or İ
    Oem8 = 0xDF,        // * (Not numpad)
    Oem102 = 0xE2,      // < >
    ProcessKey = 0xE5,
    Packet = 0xE7,
    Attn = 0xF6,
    CrSel = 0xF7,
    ExSel = 0xF8,
    EraseEof = 0xF9,
    Play = 0xFA,
    Zoom = 0xFB,
    NoName = 0xFC,
    Pa1 = 0xFD,
    OemClear = 0xFE
}